import type { Metadata } from 'next'
import { Providers } from './(home)/providers'
import { Locale } from '../../../i18n-config'

import '../globals.css'

export const metadata: Metadata = {
  title: 'Personal Profile - Diko Mahendra',
  description: 'Generated by next app dir',
}

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode
  params: { lang: Locale }
}>) {
  return (
    <html lang={lang} suppressHydrationWarning>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body className="dark:bg-gray-800">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
