import type { Metadata } from 'next'
import { Providers } from './(home)/providers'
import dynamic from 'next/dynamic'

const Header = dynamic(() => import('@/components/Header'), { ssr: false })

import { Locale } from '@@/i18n-config'
import { getDictionary } from '@@/get-dictionary'
import '@/app/globals.css'
import Head from 'next/head'

export const metadata: Metadata = {
  title: 'Personal Profile - Diko Mahendra',
  description: 'Generated by next app dir',
  authors: [{ name: 'Diko Mahendra', url: 'https://github.com/DikoMahendraa' }],
  twitter: {
    card: 'summary_large_image',
    title: 'Hi Everyone — I am Diko Mahendra',
    site: 'https://cocome.vercel.app/',
    description:
      'a frontend developer with more than 3 years of experience, building web-based applications and also mobile applications. using javascript typescript, implementing clean code and reusable code, working with a team. and ready to adjust to the technology needed by the company.',
    creator: '@dikomahendra',
    images: ['/og-cover.png'],
  },
}

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode
  params: { lang: Locale }
}>) {
  const t = await getDictionary(lang)

  return (
    <html lang={lang} suppressHydrationWarning>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>Hi Everyone — I am Diko Mahendra</title>
        <meta name="title" content="Hi Everyone — I am Diko Mahendra" />
        <meta
          name="description"
          content="a frontend developer with more than 3 years of experience, building web-based applications and also mobile applications. using javascript typescript, implementing clean code and reusable code, working with a team. and ready to adjust to the technology needed by the company."
        />

        {/* <!-- Open Graph / Facebook --> */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://cocome.vercel.app/" />
        <meta property="og:title" content="Hi Everyone — I am Diko Mahendra" />
        <meta
          property="og:description"
          content="a frontend developer with more than 3 years of experience, building web-based applications and also mobile applications. using javascript typescript, implementing clean code and reusable code, working with a team. and ready to adjust to the technology needed by the company."
        />
        <meta property="og:image" content="/og-cover.png" />
      </Head>

      <body className="dark:bg-gray-800 min-h-screen relative">
        <Providers>
          <Header content={t.profile.navbar} lang={lang} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
