import type { Metadata } from 'next'
import { Providers } from './providers'
import './globals.css'

export const metadata: Metadata = {
  title: 'Personal Profile - Diko Mahendra',
  description: 'Generated by next app dir',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body className="dark:bg-gray-800">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
